Repository Saverio976/Raytracer, pull requests merged in 2023-05, with the labels that each got.

#202 184 faire un readme qui explique comment utiliser le programme
  .github/workflows/docs.yml
  .github/workflows/mirror.yml
  .gitignore
  MaterialsPlugins/.gitkeep
  PluginsExt/AmbientLight/AmbientLightEntity.cpp
  PluginsExt/Cone/ConeEntity.cpp
  PluginsExt/Cylinder/CylinderEntity.cpp
  PluginsExt/LimitedCone/LimitedConeEntity.cpp
  PluginsExt/LimitedCylinder/LimitedCylinderEntity.cpp
  PluginsExt/LimitedPlane/LimitedPlaneEntity.cpp
  PluginsExt/LimitedPlane/LimitedPlaneEntity.hpp
  PluginsExt/Plane/PlaneEntity.cpp
  PluginsExt/Plane/PlaneEntity.hpp
  PluginsExt/PointLight/PointLightEntity.cpp
  PluginsExt/Sphere/SphereEntity.cpp
  README.md
  documentation/Doxyfile
  documentation/ambientlight1-basic.png
  documentation/cone1-basic-limited.png
  documentation/cone1-basic.png
  documentation/cylinder1-basic-limited.png
  documentation/cylinder1-basic.png
  documentation/disk2-basic.png
  documentation/plan2-basic-limited.png
  documentation/plan2-basic.png
  documentation/pointlight1-basic.png
  documentation/reprere.png
  documentation/sphere1-basic.png
  documentation/spotlight1-basic.png
  documentation/testSceneFollowUp.png
  documentation/uml.dox
  tests/documentation/ambientlight.yaax
  tests/documentation/cone-limited.yaax
  tests/documentation/cone.yaax
  tests/documentation/cylinder-limited.yaax
  tests/documentation/cylinder.yaax
  tests/documentation/disk.yaax
  tests/documentation/plan-limited.yaax
  tests/documentation/plan.yaax
  tests/documentation/pointlight.yaax
  tests/documentation/sphere.yaax
  tests/documentation/spotlight.yaax
Labels: todo

#205 [Fix] (CICD/Docs) : bad path
  .github/workflows/docs.yml
Labels: CICD

#214 Modification Cylinder et LimitedCylinder
  PluginsExt/Cylinder/CylinderEntity.cpp
  PluginsExt/LimitedCylinder/LimitedCylinderEntity.cpp
  tests/sceneYou.yaax
Labels: todo

#216 Ajout du chessboard
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/ChessBoardMaterial/CMakeLists.txt
  PluginsExt/ChessBoardMaterial/ChessBoardCreator.cpp
  PluginsExt/ChessBoardMaterial/ChessBoardCreator.hpp
  PluginsExt/ChessBoardMaterial/ChessBoardMaterial.cpp
  PluginsExt/ChessBoardMaterial/ChessBoardMaterial.hpp
  PluginsExt/ChessBoardMaterial/EntryPoint.cpp
  PluginsExt/ZebraMaterial/CMakeLists.txt
  PluginsExt/ZebraMaterial/EntryPoint.cpp
  PluginsExt/ZebraMaterial/ZebraCreator.cpp
  PluginsExt/ZebraMaterial/ZebraCreator.hpp
  PluginsExt/ZebraMaterial/ZebraMaterial.cpp
  PluginsExt/ZebraMaterial/ZebraMaterial.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  tests/sceneDamier.yaax
Labels: todo

#215 179 faire le triangleentity
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/Triangle/CMakeLists.txt
  PluginsExt/Triangle/EntryPoint.cpp
  PluginsExt/Triangle/TriangleCreator.cpp
  PluginsExt/Triangle/TriangleCreator.hpp
  PluginsExt/Triangle/TriangleEntity.cpp
  PluginsExt/Triangle/TriangleEntity.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Entities/Transform/Vector3f.cpp
  src/Entities/Transform/Vector3f.hpp
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Entities/CMakeLists.txt
  src/Plugins/Filters/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  tests/triangleTest.yaax
Labels: todo

#198 Faire l'interface graphique
  Assets/arial.ttf
  PluginsExt/Camera/Basic/CameraEntity.cpp
  PluginsExt/Camera/Basic/CameraEntity.hpp
  PluginsExt/Camera/Cluster/CameraClusterEntity.cpp
  PluginsExt/Camera/Cluster/CameraClusterEntity.hpp
  PluginsExt/Camera/FullCustom/CameraCustomEntity.cpp
  PluginsExt/Camera/FullCustom/CameraCustomEntity.hpp
  PluginsExt/Triangle/EntryPoint.cpp
  src/CMakeLists.txt
  src/Display/CMakeLists.txt
  src/Display/Display.cpp
  src/Display/Display.hpp
  src/Display/IDisplayModule.hpp
  src/Display/Modules/CMakeLists.txt
  src/Display/Modules/CanvasModule.cpp
  src/Display/Modules/CanvasModule.hpp
  src/Display/Modules/ProgressModule.cpp
  src/Display/Modules/ProgressModule.hpp
  src/Entities/ICamera.hpp
  src/ILogger.hpp
  src/Images/Color.cpp
  src/Images/Color.hpp
  src/Images/Image.cpp
  src/Images/Image.hpp
  src/Logger.cpp
  src/Logger.hpp
  src/Main.cpp
  src/Scenes/CMakeLists.txt
  src/Scenes/Scene.cpp
  src/Scenes/Scene.hpp
  tests/sceneYou.yaax
  tests/testSfml.yaax
Labels: todo

#218 217 faire le torus
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/Torus/CMakeLists.txt
  PluginsExt/Torus/EntryPoint.cpp
  PluginsExt/Torus/TorusCreator.cpp
  PluginsExt/Torus/TorusCreator.hpp
  PluginsExt/Torus/TorusEntity.cpp
  PluginsExt/Torus/TorusEntity.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Entities/CMakeLists.txt
  src/Plugins/Filters/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  tests/torusTest.yaax
Labels: todo

#220 [Feat] (Plugins) : use ./plugins
  CMakeLists.txt
  EntitiesPlugins/.gitkeep
  FiltersPlugins/.gitkeep
  MaterialsPlugins/.gitkeep
  src/Main.cpp
  src/Parameters.cpp
  src/Parameters.hpp
  src/Scenes/SceneLoader.cpp
  tests/sceneDamier.yaax
Labels: todo

#221 Ajouter le matériel transparence
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/Disk/DiskEntity.cpp
  PluginsExt/LimitedPlane/LimitedPlaneEntity.cpp
  PluginsExt/PointLight/PointLightEntity.cpp
  PluginsExt/SpotLight/SpotLightEntity.cpp
  PluginsExt/TransparencyMaterial/CMakeLists.txt
  PluginsExt/TransparencyMaterial/EntryPoint.cpp
  PluginsExt/TransparencyMaterial/TransparencyCreator.cpp
  PluginsExt/TransparencyMaterial/TransparencyCreator.hpp
  PluginsExt/TransparencyMaterial/TransparencyMaterial.cpp
  PluginsExt/TransparencyMaterial/TransparencyMaterial.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  tests/sceneTransparencyMaterial.yaax
Labels: todo

#223 [Feat] (Main) : add Ctrl+C handled in console mode
  src/Images/ImagePipeLine.cpp
  src/Main.cpp
  src/Main.hpp
  src/Scenes/ISceneState.hpp
  src/Scenes/Scene.cpp
  src/Scenes/Scene.hpp
Labels: todo

#224 [Feat] (Logger) : add colors
  src/Logger.cpp
Labels: todo

#226 Ajout du MirrorMaterial
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/MirrorMaterial/CMakeLists.txt
  PluginsExt/MirrorMaterial/EntryPoint.cpp
  PluginsExt/MirrorMaterial/MirrorCreator.cpp
  PluginsExt/MirrorMaterial/MirrorCreator.hpp
  PluginsExt/MirrorMaterial/MirrorMaterial.cpp
  PluginsExt/MirrorMaterial/MirrorMaterial.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  tests/sceneMirrorMaterial.yaax
  tests/sceneMirrorMaterial2.yaax
Labels: todo

#228 180 faire le objentity
  CMakeLists.txt
  PluginsExt/CMakeLists.txt
  PluginsExt/Obj/CMakeLists.txt
  PluginsExt/Obj/EntryPoint.cpp
  PluginsExt/Obj/ObjCreator.cpp
  PluginsExt/Obj/ObjCreator.hpp
  PluginsExt/Obj/ObjEntity.cpp
  PluginsExt/Obj/ObjEntity.hpp
  src/CMakeLists.txt
  src/Entities/CMakeLists.txt
  src/Entities/Transform/CMakeLists.txt
  src/Factories/CMakeLists.txt
  src/Filters/CMakeLists.txt
  src/Images/CMakeLists.txt
  src/Plugins/CMakeLists.txt
  src/Plugins/Entities/CMakeLists.txt
  src/Plugins/Filters/CMakeLists.txt
  src/Plugins/Materials/CMakeLists.txt
  src/Scenes/CMakeLists.txt
  src/Scenes/Scene.cpp
  src/Scenes/SceneLoader.cpp
  tests/obj/cube.obj
  tests/obj/cube_younes.obj
  tests/obj/cube_younes_big.obj
  tests/testObj.yaax
Labels: todo

#233 [Feat] (Display) : take screnshot
  src/Display/Modules/CanvasModule.cpp
  src/Display/Modules/CanvasModule.hpp
  src/Main.cpp
  src/Scenes/Scene.cpp
  src/Scenes/Scene.hpp
Labels: todo

#231 166 faire des scènes
  Scenes/Scene_01.yaax
  scenes/documentation/ambientlight.yaax
  scenes/documentation/camera-cluster1.yaax
  scenes/documentation/camera-cluster2.yaax
  scenes/documentation/camera-cluster5.yaax
  scenes/documentation/chessboardmaterial.yaax
  scenes/documentation/cone-limited.yaax
  scenes/documentation/cone.yaax
  scenes/documentation/cylinder-limited.yaax
  scenes/documentation/cylinder.yaax
  scenes/documentation/disk.yaax
  scenes/documentation/plainmaterial.yaax
  scenes/documentation/plan-limited.yaax
  scenes/documentation/plan.yaax
  scenes/documentation/pointlight.yaax
  scenes/documentation/sphere.yaax
  scenes/documentation/spotlight.yaax
  scenes/documentation/ssaax4.yaax
  scenes/documentation/torus.yaax
  scenes/documentation/transparencymaterial.yaax
  scenes/documentation/triangle.yaax
  scenes/documentation/zebramaterial.yaax
  scenes/generateScreens.sh
  scenes/sceneBasic1.yaax
  scenes/sceneBasic2.yaax
  scenes/sceneBasic3.yaax
  scenes/sceneBasic4.yaax
  scenes/sceneDamier.yaax
  scenes/sceneLimitedCylinder.yaax
  scenes/sceneMirrorMaterial.yaax
  scenes/sceneMirrorMaterial2.yaax
  scenes/sceneObj.yaax
  scenes/sceneRefractionMaterial.yaax
  scenes/sceneTransparencyMaterial.yaax
Labels: todo

#234 Release
  .github/release.yml
  .github/workflows/release.yml
  Assets/scene4kpyramide_0.png
  README.md
  scenes/4K/basic1.yaax
  scenes/4K/pyramide.yaax
  src/Images/Color.cpp
  src/Images/Color.hpp
  src/Images/Image.cpp
Labels: release
